version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/before.sh
  AfterInstall:
    - location: scripts/after.sh
  ApplicationStart:
    - location: scripts/start.sh
  ApplicationStop:
    - location: scripts/stop.sh
